//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Genre
    {
        public int ID { get; set; }
        public int IDBook { get; set; }
        public int IDGenre { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
