//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public Nullable<int> IDUserA { get; set; }
        public Nullable<int> IDBook { get; set; }
        public string Text { get; set; }
        public double Rating { get; set; }
        public Nullable<bool> Freez { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
